---

- hosts: server
  tasks:
  - include_role:
      name: informaticsmatters.infrastructure_user
    vars:
      iu_action: create
      iu_type: realm
      iu_hostname: keycloak.example.com
      iu_namespace: im-infra
      iu_realm: blob
      iu_realm_manager: manager
      iu_realm_manager_password: abc00000
      iu_admin_user: admin
      iu_admin_password: blob1234
