---

- hosts: server
  tasks:
  - include_role:
      name: informaticsmatters.infrastructure_user
    vars:
      iu_action: create
      iu_type: role
      iu_hostname: keycloak.example.com
      iu_realm: blob
      iu_realm_manager: manager
      iu_realm_manager_password: abc00000
      iu_roles:
      - name: standard-user
        default: yes
      - name: blob
