---
language: python
python:
- '3.7'
install:
- pip install -r build-requirements.txt
- pip install -r requirements.txt
script:
- yamllint .
- find . -type f -iname '*.yaml.j2' -exec yamllint {} \;
- ansible-lint
