---

- include_tasks: prep.yaml

# Go...

- name: Check action
  assert:
    that:
    - iu_action in ['create', 'delete']
    - iu_type in ['realm', 'role', 'user']

# Execute the desired action on the required type...

- include_tasks: "{{ iu_action }}-{{ iu_type }}.yaml"
